//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brown_Prepress_Automation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastFolder {
            get {
                return ((string)(this["lastFolder"]));
            }
            set {
                this["lastFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\HOTFOLDER\\")]
        public string hotFolder {
            get {
                return ((string)(this["hotFolder"]));
            }
            set {
                this["hotFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\ERRORS\\")]
        public string errorFolder {
            get {
                return ((string)(this["errorFolder"]));
            }
            set {
                this["errorFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\ARCHIVE\\")]
        public string archiveFolder {
            get {
                return ((string)(this["archiveFolder"]));
            }
            set {
                this["archiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool updateCheck {
            get {
                return ((bool)(this["updateCheck"]));
            }
            set {
                this["updateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sendEmails {
            get {
                return ((bool)(this["sendEmails"]));
            }
            set {
                this["sendEmails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool debugOn {
            get {
                return ((bool)(this["debugOn"]));
            }
            set {
                this["debugOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
        public string tempDir {
            get {
                return ((string)(this["tempDir"]));
            }
            set {
                this["tempDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Parts\\")]
        public string parts {
            get {
                return ((string)(this["parts"]));
            }
            set {
                this["parts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\HOTFOLDER - BLUELINE\\")]
        public string bluelineOutput {
            get {
                return ((string)(this["bluelineOutput"]));
            }
            set {
                this["bluelineOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bii-owa.brownind.com")]
        public string exchangeServer {
            get {
                return ((string)(this["exchangeServer"]));
            }
            set {
                this["exchangeServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mhoward")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mh4094")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("matt.howard@brownind.com")]
        public string fromEmail {
            get {
                return ((string)(this["fromEmail"]));
            }
            set {
                this["fromEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string printer {
            get {
                return ((string)(this["printer"]));
            }
            set {
                this["printer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>pam.mcatee@brownind.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection tuftexEmailList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["tuftexEmailList"]));
            }
            set {
                this["tuftexEmailList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\HOTFOLDER\\Armstrong\\")]
        public string armstrongHotfolder {
            get {
                return ((string)(this["armstrongHotfolder"]));
            }
            set {
                this["armstrongHotfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\ERROR\\Armstrong\\")]
        public string armstrongErrorFolder {
            get {
                return ((string)(this["armstrongErrorFolder"]));
            }
            set {
                this["armstrongErrorFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\HOTFOLDER\\Nourison\\")]
        public string nourisonHotfolder {
            get {
                return ((string)(this["nourisonHotfolder"]));
            }
            set {
                this["nourisonHotfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\ERROR\\Nourison\\")]
        public string nourisonErrorFolder {
            get {
                return ((string)(this["nourisonErrorFolder"]));
            }
            set {
                this["nourisonErrorFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\HOTFOLDER\\Shaw\\")]
        public string shawHotfolder {
            get {
                return ((string)(this["shawHotfolder"]));
            }
            set {
                this["shawHotfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\ERROR\\Shaw\\")]
        public string shawErrorFolder {
            get {
                return ((string)(this["shawErrorFolder"]));
            }
            set {
                this["shawErrorFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Customers\\Armstrong\\PDFs\\")]
        public string armstrongPdfs {
            get {
                return ((string)(this["armstrongPdfs"]));
            }
            set {
                this["armstrongPdfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\XMF HOTFOLDERS\\OMEGA DIE 284\\")]
        public string XMF5x1_75 {
            get {
                return ((string)(this["XMF5x1_75"]));
            }
            set {
                this["XMF5x1_75"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\Archive\\Armstrong\\")]
        public string armstrongArchiveFolder {
            get {
                return ((string)(this["armstrongArchiveFolder"]));
            }
            set {
                this["armstrongArchiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\Archive\\Shaw\\")]
        public string shawArchiveFolder {
            get {
                return ((string)(this["shawArchiveFolder"]));
            }
            set {
                this["shawArchiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\Archive\\Nourison\\")]
        public string nourisonArchiveFolder {
            get {
                return ((string)(this["nourisonArchiveFolder"]));
            }
            set {
                this["nourisonArchiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\CALDERA HOTFOLDERS\\STYRENE - HQ POP\\")]
        public string nourisonHpOutput {
            get {
                return ((string)(this["nourisonHpOutput"]));
            }
            set {
                this["nourisonHpOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Customers\\Nourison\\POP\\Nourison POP\\")]
        public string nourisonPdfs {
            get {
                return ((string)(this["nourisonPdfs"]));
            }
            set {
                this["nourisonPdfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\PrintablePDFs\\Shaw Hardsurfaces\\Shaw Proofs\\")]
        public string shawPdfs {
            get {
                return ((string)(this["shawPdfs"]));
            }
            set {
                this["shawPdfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.19.200\\Watched Folders\\Move to Caldera - White Paper\\")]
        public string shawHpOutput {
            get {
                return ((string)(this["shawHpOutput"]));
            }
            set {
                this["shawHpOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\Printable Hotfolders\\Indigo 5600\\Printable\\")]
        public string shawIndigo5600 {
            get {
                return ((string)(this["shawIndigo5600"]));
            }
            set {
                this["shawIndigo5600"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\Printable Hotfolders\\Indigo 6800\\Printable\\")]
        public string shawIndigo6800 {
            get {
                return ((string)(this["shawIndigo6800"]));
            }
            set {
                this["shawIndigo6800"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Customers\\Tuftex\\Labels\\Pdfs\\")]
        public string tuftexPdf {
            get {
                return ((string)(this["tuftexPdf"]));
            }
            set {
                this["tuftexPdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Customers\\Tuftex\\Labels\\Jpgs\\")]
        public string tuftexJpg {
            get {
                return ((string)(this["tuftexJpg"]));
            }
            set {
                this["tuftexJpg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\HOTFOLDER - TUFTEX LABELS\\")]
        public string tuftexXmlHotfolder {
            get {
                return ((string)(this["tuftexXmlHotfolder"]));
            }
            set {
                this["tuftexXmlHotfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\HOTFOLDER - TUFTEX MISC LABELS\\")]
        public string tuftexMiscHotfolder {
            get {
                return ((string)(this["tuftexMiscHotfolder"]));
            }
            set {
                this["tuftexMiscHotfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool nourisonCommon {
            get {
                return ((bool)(this["nourisonCommon"]));
            }
            set {
                this["nourisonCommon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Customers\\AHF Products\\Pdfs\\")]
        public string armstrongAHFpdfs {
            get {
                return ((string)(this["armstrongAHFpdfs"]));
            }
            set {
                this["armstrongAHFpdfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\XMF HOTFOLDERS\\ARMSTRONG 16x16\\")]
        public string XMF16x16 {
            get {
                return ((string)(this["XMF16x16"]));
            }
            set {
                this["XMF16x16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>irene.sisson@brownind.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection armstrongEmailList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["armstrongEmailList"]));
            }
            set {
                this["armstrongEmailList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.19.5\\Log\\")]
        public string prepressHotfolder {
            get {
                return ((string)(this["prepressHotfolder"]));
            }
            set {
                this["prepressHotfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool workerWait {
            get {
                return ((bool)(this["workerWait"]));
            }
            set {
                this["workerWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string downloadPdfName {
            get {
                return ((string)(this["downloadPdfName"]));
            }
            set {
                this["downloadPdfName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\Output1\\BROWN AUTOMATION PROGRAM\\XMF HOTFOLDERS\\")]
        public string xmfHotfolders {
            get {
                return ((string)(this["xmfHotfolders"]));
            }
            set {
                this["xmfHotfolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.45\\PrintablePDFs\\Shaw Hardsurfaces\\Shaw Proofs\\")]
        public string shawPdfsOld {
            get {
                return ((string)(this["shawPdfsOld"]));
            }
            set {
                this["shawPdfsOld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>matt.howard@brownind.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection shawEmailList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["shawEmailList"]));
            }
            set {
                this["shawEmailList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection shawCheckList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["shawCheckList"]));
            }
            set {
                this["shawCheckList"] = value;
            }
        }
    }
}
